### Random snippets for checking and editing main code

In [1]:
%matplotlib inline
from __future__ import division
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import *
import seaborn as sns
import matplotlib.dates as mdates
#plt.style.use('seaborn-colorblind')
import pickle
import sys
sys.path.append("..")
import DispaSET as ds

In [2]:
from DispaSET.postprocessing import postprocessing as post
reload(post)

<module 'DispaSET.postprocessing.postprocessing' from '../DispaSET/postprocessing/postprocessing.pyc'>

In [3]:
pd.options.display.max_rows = 60   #default 60 (None)
pd.options.display.max_columns = 60   #default 60 (None)
np.set_printoptions(threshold=1000)   #default 1000 (np.inf)

In [4]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/neww_int/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

Results1 = gdx_to_dataframe(gdx_to_list(gams_dir, resultfile, varname='all', verbose=True), fixindex=True,verbose=True)

[INFO    ] (gdx_to_list): Loading gdx file ../Simulations/neww_int/Results.gdx took 0.275912046432s
[INFO    ] (gdx_to_dataframe): Time to convert to dataframes: 0.112210988998s


In [4]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub4/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

Results1 = gdx_to_dataframe(gdx_to_list(gams_dir, resultfile, varname='all', verbose=True), fixindex=True,verbose=True)

[INFO    ] (gdx_to_list): Loading gdx file ../Simulations/simulation_GCC_sub4/Results.gdx took 9.80907988548s
[INFO    ] (gdx_to_dataframe): Time to convert to dataframes: 3.2671380043s


In [19]:
Results1['NodeFuelPower']['BA']['GAS'].values+(1.3*Results1['NodeFuelPower']['BA']['GAS'].values)

array([25.07367243, 25.07367243, 25.07367243, ..., 25.07367243,
       25.07367243, 25.07367243])

In [6]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_int4/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)
list_gdx['NodeFuelConsumption'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelConsumption']]
list_gdx['NodeFuelCost'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelCost']]
AAA = list_gdx['NodeFuelPower']
list_gdx['NodeFuelPower'] = [[ele[0],ele[2],ele[3]]for ele in list_gdx['NodeFuelPower']]
Results = gdx_to_dataframe(list_gdx, fixindex=True,verbose=True)

[INFO    ] (gdx_to_list): Loading gdx file ../Simulations/simulation_GCC_int4/Results.gdx took 9.32777285576s
[INFO    ] (gdx_to_dataframe): Time to convert to dataframes: 24.862046957s


In [1]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub_int5/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)

for element in list_gdx.keys():
    try:
        if len(list_gdx[element][0])==4:
            list_gdx[element] = [[ele[0], ele[2], ele[3]] for ele in list_gdx[element]]
    except:
        pass
Results = gdx_to_dataframe(list_gdx, fixindex=True,verbose=True)

ImportError: No module named DispaSET.misc.gdx_handler

In [ ]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
resultfile = '../Simulations/simulation_GCC_sub_int5/Results.gdx'
gams_dir = '/Applications/GAMS26.1/sysdir'

list_gdx = gdx_to_list(gams_dir, resultfile, varname='all', verbose=True)
list_gdx['PowerFlow']


In [ ]:
vars3 = set()
for element in list_gdx['PowerFlow']:
    if not element[1] in vars3:
        vars3.add(element[1])
vars3 = list(vars3)

In [ ]:
vars3
AA=pd.DataFrame(columns=['AA','BB'],index=vars3)

In [ ]:
AA
idx = pd.IndexSlice
AA.loc[idx[vars3], idx['AA', 'BB']]

In [ ]:
AA = pd.DataFrame(columns=['ABC','BUR'])

CC={'ABC':[3,6,7]}

AA['ABC'] = CC

In [ ]:
AA

In [ ]:
vars1 = set()
vars1.add('45')
contries = ['BA','QA','KSA']
vars1 = list(vars1)
series_1 = list(vars1 * len(contries))

In [ ]:
series_1

In [ ]:
vars1 = set()
vars1.add('45')
vars1.add('34')
len(vars1)

for i in vars1:
    print i

In [60]:
import xlrd
wb = xlrd.open_workbook(filename='/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
sheet = wb.sheet_by_name('main')

Countries_list = [item.value.encode("utf-8") for item in sheet.row_slice(rowx=155, start_colx=1, end_colx=100)]
Countries_list = [x for x in values if x != '']
Countries_list


['UAE', 'KSA', 'OM', 'BA', 'QA', 'KW', 'Egypt', 'Jordan', 'Yemen', 'Iraq']

In [61]:
B = {}
B = B.fromkeys(Countries_list)

In [62]:
B

{'BA': None,
 'Egypt': None,
 'Iraq': None,
 'Jordan': None,
 'KSA': None,
 'KW': None,
 'OM': None,
 'QA': None,
 'UAE': None,
 'Yemen': None}

In [88]:
import datetime as dt
idx_std = pd.DatetimeIndex(start=pd.datetime(*(2016, 1, 1, 0, 0, 0)), end=pd.datetime(*(2016, 12, 31, 23, 0, 0)),
                           freq='1h')
idx_utc_noloc = idx_std - dt.timedelta(hours=1)

In [89]:
len(idx_utc_noloc)

8784

In [100]:
path5 = '../Simulations/Months_Data.csv' 
AAA.resample('M',how='mean').to_csv(path5)


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:2: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()
  


In [1]:
FirstCell = 'String'
isinstance(FirstCell, basestring)

True

In [4]:
tmp = ['No file']
isinstance(tmp, pd.DataFrame)

False

In [3]:
import xlrd
wb = xlrd.open_workbook(filename='/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
sheet = wb.sheet_by_name('main')

ufo = pd.read_csv('/Users/abdullahalawad/Dropbox (MIT)/CCES/2017/Energy/Regional trade/UC&ED/Dispa-SET/PycharmProjects/UC/Simulations/ConfigGCC.xlsx')
ufo


ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2


In [37]:
for i,zone in enumerate(n):
    print i

0
1
2
3
4
5


In [31]:
n = ['BA','KW','OM','UAE','QA','KSA']
f = ['OIL','HFO','GAS','DSL']
t = ['Int', 'Sub']
C = [n,f,t]
tmp = np.zeros([len(a) for a in C])

for i,zone in enumerate(n):
    for j,fuel in enumerate(f):
        for typ in t:
            if typ=='Int' and isinstance(FuelPricesPerZone['International'][fuel], (int, long, float, complex)):
                tmp[i][j][0] = FuelPricesPerZone['International'][fuel]
            elif typ=='Sub' and isinstance(FuelPricesPerZone[zone][fuel], (int, long, float, complex)):
                tmp[i][j][1] = FuelPricesPerZone[zone][fuel]

FuelPricesPerZone[zone][FuelEntries[fuel]]
values = np.array([
        [dd_begin.year, dd_begin.month, dd_begin.day],
        [dd_end.year, dd_end.month, dd_end.day],
        [0, 0, config['HorizonLength']],
        [0, 0, config['LookAhead']]

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
np.random.rand(1)[0]

0.21440224299160293

In [37]:
n = ['FirstDay','LastDay','RollingHorizon Length','RollingHorizon LookAhead']
f = ['year','month','day']
C = [n,f]
AA = np.zeros([len(a) for a in C])

for zone in 

values = np.array([
        [dd_begin.year, dd_begin.month, dd_begin.day],
        [dd_end.year, dd_end.month, dd_end.day],
        [0, 0, config['HorizonLength']],
        [0, 0, config['LookAhead']]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
B = {}
B['C'] = {}
B['C']['K'] = 1
B

{'C': {'K': 1}}

In [43]:
from DispaSET.misc.gdx_handler import gdx_to_list, gdx_to_dataframe, get_gams_path
AA = pd.read_csv('../Database/FuelPrices/FuelPrices.csv', header=0, index_col=0)
AA['International']['NUC']


nan

In [45]:
isinstance(AA['International']['OIL'], (int, long, float, complex)) and AA['International']['OIL'] > 0

True

In [47]:
FuelEntries2 = {'BIO': 'PriceOfBiomass 2', 'GAS': 'PriceOfGas 2', 'HRD': 'PriceOfBlackCoal 2', 'LIG': 'PriceOfLignite 2',
                   'NUC': 'PriceOfNuclear 2', 'OIL': 'PriceOfCrudeOil 2', 'PEA': 'PriceOfPeat 2', 'DSL': 'PriceOfDiesel 2',
                   'HFO': 'PriceOfHFO 2', 'MSW': 'PriceOfMunicipalSolidWaste 2', 'LFG': 'PriceOfLandFillGas 2'}
FuelEntries2['BIO']

'PriceOfBiomass 2'